# Generated by Django 6.0.1 on 2026-03-02 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('futsal', '0003_remove_futsal_images_futsalimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Snapshot price at booking time', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled'), ('OCCUPIED', 'occupied'), ('COMPLETED', 'completed')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('FAILED', 'failed'), ('REFUNDED', 'refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='futsal.futsal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancelFine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine', models.DecimalField(decimal_places=2, help_text='Final cancellation fine (snapshot)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_fine', to='booking.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof', models.ImageField(upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='booking.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='futsal.futsal')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['futsal', 'start_time', 'end_time'], name='booking_tim_futsal__4d475d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['futsal', 'required_date'], name='booking_boo_futsal__b28fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['user', 'status'], name='booking_boo_user_id_6ca2c5_idx'),
        ),
    ]
