# Generated by Django 6.0.1 on 2026-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelfine',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('FAILED', 'failed'), ('REFUNDED', 'refunded')], default='PENDING', max_length=20),
        ),
    ]
