# Generated by Django 6.0.1 on 2026-03-03 09:24

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cancelfine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='proof',
            field=models.ImageField(upload_to=booking.models.payment_proof_path),
        ),
    ]
