# Generated by Django 6.0.1 on 2026-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_paymentproof_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(choices=[('HOURLY', 'hourly'), ('EVENT', 'event')], default='HOURLY', max_length=20),
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
