# Generated by Django 6.0.1 on 2026-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='futsal_images/'),
        ),
    ]
