# Generated by Django 6.0.1 on 2026-03-02 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_futsal_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='images',
        ),
        migrations.CreateModel(
            name='FutsalImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='futsal_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='futsal.futsal')),
            ],
        ),
    ]
