# Generated by Django 6.0.1 on 2026-03-03 09:24

import futsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_remove_futsal_images_futsalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalimage',
            name='image',
            field=models.ImageField(upload_to=futsal.models.futsal_image_path),
        ),
    ]
