# Generated by Django 6.0.1 on 2026-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_alter_futsalimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='futsalimage',
            name='image_type',
            field=models.CharField(choices=[('Picture', 'Picture'), ('Document', 'Document')], default='Picture', max_length=50),
        ),
    ]
