# Generated by Django 6.0.1 on 2026-03-05 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_futsal_approval_status_futsalimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='closing_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futsal',
            name='opening_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futsal',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futsal',
            name='washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futsal',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
