# Generated by Django 6.0.1 on 2026-03-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_futsal_closing_time_futsal_opening_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsalimage',
            name='image_type',
        ),
    ]
