# Generated by Django 6.0.1 on 2026-03-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0007_remove_futsalimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='city',
        ),
    ]
