# Generated by Django 6.0.1 on 2026-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0008_remove_futsal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='venue_type',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Indoor', max_length=20),
        ),
    ]
