# Generated by Django 6.0.1 on 2026-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_document_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hour_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
