# Generated by Django 6.0.1 on 2026-03-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_document_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
