# Generated by Django 6.0.1 on 2026-03-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_hour_played_user_matches_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
